# version: "3"
services:
  dasktest:
    container_name: dasktest
    hostname: dasktest
    image: mydask
    # entrypoint: /home/freekostageo/Desktop/Productivity\ scripts/entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./data/:/home/data/
      - ./notebooks/:/home/notebooks/
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    # depends_on:
    #   - eo_mongodb
  # eo_mongodb:
  #   container_name: eo_mongo
  #   hostname: dasktest
  #   image: mongo
  #   volumes:
  #     - mongoVolume:/data/db
  #   restart: unless-stopped
  #   stdin_open: false # equivalent to docker run -i
  #   tty: false        # equivalent to docker run -t
  #   ports:
  #     - "127.0.0.1:27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   command: --quiet
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"
# volumes:
#   mongoVolume:
